name: pop_dart
version: 0.0.1+1
description: A delicious Dart library
homepage: https://github.com/dartsidedev/pop_dart
issue_tracker: https://github.com/dartsidedev/pop_dart/issues
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.6.4